POST http://localhost:3000/adduser
Content-Type: application/json

{
    "full_name": "User One",
    "user_id": "user1",
    "expenses" : [],
    "groups": [{
    "group_id": "group1",
    "name": "Example Group",
    "expenses": [
      {
        "reason": "Dinner",
        "amount": 120,
        "user_id": "user1",
        "group_id": "group1",
        "expense_id": "expense1"
      },
      {
        "reason": "Taxi",
        "amount": 60,
        "user_id": "user2",
        "group_id": "group1",
        "expense_id": "expense2"
      }
    ]}] 
}

###
POST http://localhost:3000/addgroup
Content-Type: application/json

{
    "group_id": "group1",
    "name": "Example Group",
    "expenses": [
        { "reason": "Dinner", "amount": 120, "user_id": "user1", "group_id": "group1", "expense_id": "expense1" },
        { "reason": "Taxi", "amount": 60, "user_id": "user2", "group_id": "group1", "expense_id": "expense2" }
    ],
    "people": [
        { "full_name": "User One", "user_id": "user1", "expenses": [] },
        { "full_name": "User Two", "user_id": "user2", "expenses": [] },
        { "full_name": "User Three", "user_id": "user3", "expenses": [] }
    ]
}


###
POST http://localhost:3000/addexpense
Content-Type: application/json

{
  "reason": "test",
  "expense_id": "1",
  "user_id": "user1",
  "group_id": "group1",
  "amount": 100
}